FUNCTION BOUND_FUNC ( COORD )
  IMPLICIT NONE
  DOUBLE PRECISION, DIMENSION(4)             :: BOUND_FUNC
  DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: COORD
  BOUND_FUNC = 0.0D0
END FUNCTION BOUND_FUNC
